// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Theater.Context;

namespace Theater.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Theater.Models.Dashboard.Models.Actor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "William",
                            LastName = "Shakespeare"
                        },
                        new
                        {
                            Id = 2L,
                            FirstName = "Michael",
                            LastName = "Ball"
                        },
                        new
                        {
                            Id = 3L,
                            FirstName = "Bal",
                            LastName = "Dhuri"
                        },
                        new
                        {
                            Id = 4L,
                            FirstName = "Harrison",
                            LastName = "Chad"
                        },
                        new
                        {
                            Id = 5L,
                            FirstName = "Leah",
                            LastName = "Clark"
                        });
                });

            modelBuilder.Entity("Theater.Models.Dashboard.Models.Play", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("ScheduleTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("Theater.Models.Dashboard.Models.PlayActor", b =>
                {
                    b.Property<long>("PkFkActorId")
                        .HasColumnType("bigint");

                    b.Property<long>("PkFkPlayId")
                        .HasColumnType("bigint");

                    b.HasKey("PkFkActorId", "PkFkPlayId");

                    b.HasIndex("PkFkPlayId");

                    b.ToTable("PlayActors");
                });

            modelBuilder.Entity("Theater.Models.Dashboard.Models.PlayActor", b =>
                {
                    b.HasOne("Theater.Models.Dashboard.Models.Actor", "Actor")
                        .WithMany("PlayActors")
                        .HasForeignKey("PkFkActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Theater.Models.Dashboard.Models.Play", "Play")
                        .WithMany("PlayActors")
                        .HasForeignKey("PkFkPlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("Theater.Models.Dashboard.Models.Actor", b =>
                {
                    b.Navigation("PlayActors");
                });

            modelBuilder.Entity("Theater.Models.Dashboard.Models.Play", b =>
                {
                    b.Navigation("PlayActors");
                });
#pragma warning restore 612, 618
        }
    }
}
